<?php

/**
 * @file
 * Drupal site-specific configuration file.
 *
 * This is a placeholder. On a live site, this file is generated by the
 * Drupal installer or managed via your hosting platform.
 */

/**
 * Load local development overrides configuration, if available.
 *
 * Create a settings.local.php file to override variables on secondary
 * (staging, development, etc.) installations of this site.
 */
if (file_exists($app_root . '/' . $site_path . '/settings.local.php')) {
  include $app_root . '/' . $site_path . '/settings.local.php';
}
